### ISSUE TITLE
Vertically center content in feature panel

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/undergraduate-admissions#2]
The "Visit WVU", "Virtual Tours", and "Meet WVU Events" patterns should vertically center the copy as seen on this page.

http://admissions.sandbox.wvu.edu/visit

The partials are `custom-patterns/admissions-feature-panel.html` and `custom-patterns/admissions-feature-panel__triptych.html`.

**Comment by zeroedin** [comment]
Don't know if you want to add http://campusmap.wvu.edu/ to the "Virtual Tour" section.

**Comment by adamjohnson** [comment]
@dustinmazon what do you think about this?

**Comment by zeroedin** [comment]
Just also to note that site will be getting brand patterns slapped on it real soon.

**Comment by dustinmazon** [comment]
I think it could work, not sure about the order. I think we should have the special events above the virtual tour. 

@adamjohnson we should use .wvu-text--center to horizontally center and create a new class in _admissions__typography.scss to vertically center using flex.

**Comment by adamjohnson** [comment]
I don't think you're going to have good results applying a single class to vertically center stuff. It'd probably have to be multiple classes.

With that in mind, should we make a utility class or just apply it in a case by case basis (aka specific to the partial)? It might be that we just apply it to the feature panel and nothing else but I'm open to other thoughts.

**Comment by adamjohnson** [comment]
Added campusmap.wvu.edu to the "Virtual Tour" section. Working on these other changes now.

http://admissions.sandbox.wvu.edu/visit
