### ISSUE TITLE
Possible Content Changes for "Request Info"

### ISSUE THREAD

**Issue by dmolsen** [wvuweb/undergraduate-admissions#29]
I feel like we need a blurb/sentence that can push someone who is looking just to contact us about any old issue. "Request Info" is a pretty big catch all. I know in the past it's about getting materials and signing up for our mailing list. It's just not completely obvious to me.

This is related to #30

**Comment by dmolsen** [comment]
@sfgwv -

Not sure if this is an editable region or not. If not post the copy and I'll get it added.

**Comment by sfgwv** [comment]
Copy updated. Make sure the general question link is what you had in mind, @dmolsen
