### ISSUE TITLE
Single column list class not working for major search results

### ISSUE THREAD

**Issue by dmolsen** [wvuweb/undergraduate-admissions#31]
Can you check on this and see what I messed up? I added the class to the `ul` but it's not changing anything.

**Comment by adamjohnson** [comment]
Be sure to have both classes applied to the ul. Not just the modifier.

**Comment by dmolsen** [comment]
Well... duh. ;)

**Comment by adamjohnson** [comment]
```
u-link-list u-link-list-—single-column <---- Dash and en dash
u-link-list u-link-list--single-column  <---- Two dashes
```

:ok_hand:

**Comment by zeroedin** [comment]
Dave needs a new editor.  Time for an [Atom](https://atom.io/) upgrade :)

**Comment by dmolsen** [comment]
it's installed on my computer....

**Comment by adamjohnson** [comment]
Do it. :+1:

**Comment by dmolsen** [comment]
Old dog. New tricks. I still use Safari too.
