### ISSUE TITLE
Possible Content Changes for "Majors Search Results"

### ISSUE THREAD

**Issue by dmolsen** [wvuweb/undergraduate-admissions#32]
Some ideas:

 - [x] Need better copy in general for the search results.
 - [x] Add the number of returned results to the copy as well

Related to #49

**Comment by dmolsen** [comment]
@sfgwv -

We need to tag team on this one too

**Comment by sfgwv** [comment]
@dmolsen - Could the number of returned results go beside the headings? e.g. Exact Matches (1), Related Matches (10) It would eliminate the need for "major(s)" in the copy below.

Copy:
Search Results
The following # major(s) matched your search for “major name.”
Sorry, we didn’t find any majors with “major name” in the title. Please try a new search.

Related Matches
We found # major(s) related to your search for “major name.”
Sorry, we didn’t find any other majors related to “major name.” Please try a new search.
