### ISSUE TITLE
Copy Change for "Menu" Dropdown

### ISSUE THREAD

**Issue by dmolsen** [wvuweb/undergraduate-admissions#38]
On mobile the navigation menu gets dropped to an expandable list. This copy might read better as "Navigation" as opposed to "Menu" or something else that reads better than just "Menu."

**Comment by dustinmazon** [comment]
I think having the menu expanded on initial load could help make the user become aware of the navigational options. I think the word "Menu" seems to be a pretty commonly used term throughout the web. I think users are familiar with the word, we could even throw in the dreaded hamburger icon for an added bonus.

I am thinking we should call it "Site Menu" for the primary navigation and then when we display the secondary nav we can use the method for the backpage header title to load in as the secondary menu heading. 

## Example:

How to Apply Menu
Academics Menu

**Comment by zeroedin** [comment]
These are things that should probably work their way back into [wvuweb/brand-patterns](https://github.com/wvuweb/brand-patterns) as well imho.

**Comment by dustinmazon** [comment]
+1

**Comment by dmolsen** [comment]
I'd be ok with "site menu." Just seems like "menu" is used when there's little space. We have a ton so figured we could be more descriptive.

**Comment by dmolsen** [comment]
Closing this out in favor of #7. I'll note the word change there.
