### ISSUE TITLE
Add support for editor config.

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/undergraduate-admissions#39]
If you haven't already done so, install the editor config package for Atom/Sublime. More on the site:

http://editorconfig.org/#download

We all gotta get on the same page. Use spaces for tabs with a count of two. New line at the end of the file, always.

**Comment by dmolsen** [comment]
Can I pull seniority on the tabs issue? ;) For the rest of the project I'll go with Atom.

**Comment by zeroedin** [comment]
:-1: spaces instead of tabs

**Comment by adamjohnson** [comment]
Spaces for the win. Sorry Dave.

Please install the editor config package for whichever editor you're using.

**Comment by dmolsen** [comment]
installed for atom

**Comment by adamjohnson** [comment]
:+1:
