### ISSUE TITLE
General Treatment of Right Nav Navigation on Backpages

### ISSUE THREAD

**Issue by dmolsen** [wvuweb/undergraduate-admissions#41]
On mobile it the right nav navigation feels like it's floating in space and just tacked on. Other ideas for addressing this? A header? Background color?

**Comment by dustinmazon** [comment]
+1 

I like the idea of having a heading and a different background.

Also checkout issue #7 for a solution on how to handle the secondary nav for mobile.

**Comment by dmolsen** [comment]
Closing this out in favor of #7. I'll add this as a comment there.
