### ISSUE TITLE
Add Lede Copy to Hero Image

### ISSUE THREAD

**Issue by dmolsen** [wvuweb/undergraduate-admissions#43]
Please write up copy and add it. I believe these are editable regions but if not you can ask us to update.

**Comment by sfgwv** [comment]
@dmolsen - It's not editable. Here's what I have for the first three:
Home -
The first thing you’ll learn here is that “impossible” is just a challenge.

How to Apply - 
Meet your future head-on: submit your application for admission.

Academics - (I changed the headline myself but didn't publish.)
If you think you’re going to passively listen and regurgitate facts, think again.

**Comment by dmolsen** [comment]
Added.
