### ISSUE TITLE
Add Webinars feature panel to Visit WVU page

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/undergraduate-admissions#5]
We don't really have content for the Webinars feature panel yet, but we can set up a new partial to include these items so that it's an easy drop-in when the time comes.

Add webinars feature panel to this page: http://admissions.sandbox.wvu.edu/visit 

Things to figure out: 

  - [x] Image
  - [x] Text/Copy
  - [x] URL for button/link

**Comment by dustinmazon** [comment]
Yeah, it should be done so that we can easily add it to other page templates as well, like the homepage or audience pages.

**Comment by adamjohnson** [comment]
c219d967856cb953b3333b42cf0520d8b55cb862 is related to this.

**Comment by adamjohnson** [comment]
This is done:

http://admissions.sandbox.wvu.edu/visit

@sfgwv If you find the copy unfit for the Webinars section, feel free to change it. It's in an editable region.

**Comment by sfgwv** [comment]
Certainly not unfit, but I did edit it. :)
