### ISSUE TITLE
More Content to Highlight on Cost & Aid

### ISSUE THREAD

**Issue by dmolsen** [wvuweb/undergraduate-admissions#55]
On cost and aid let's make sure we highlight the following:

 - [x] March 1 is the FAFSA deadline
 - [x] reduced tuition opportunties. See [the current page for examples](http://admissions.wvu.edu/pay). That could be its own section.
 - [x] the net price calculator needs to make an appearance somewhere. it's not in the copy for the calculator as well. we want to make sure we're clearly in compliance with the law on that one.

I figure @dustinmazon and @sfgwv can tag team on this one.

**Comment by sfgwv** [comment]
Content for possible new Reduced Tuition and FAFSA sections. Not saying FAFSA needs to be its own section, but I can't think of another way to work in the March 1 deadline.

Reduced Tuition
Do you live in Ohio or Washington, D.C., or study at Garrett College in Maryland? You may be eligible  for reduced tuition. We also offer specialized programs at in-state tuition rates through the Academic Common Market.
Ohio - /cost-and-aid/ohio-tuition-reciprocity-agreement
Washington, D.C. - http://osse.dc.gov/service/dc-tuition-assistance-grant-dc-tag
Garrett College - /cost-and-aid/reduced-tuition-for-garret-college-students
Academic Common Market - http://www.sreb.org/page/1304/academic_common_market.html

Free Application for Federal Student Aid
To apply for financial aid, file the FAFSA as soon as you can — preferably in January. The deadline is March 1. Use FAFSA School Code 003827 to send your information to our Morgantown campus. 
Learn About the FAFSA - http://financialaid.wvu.edu/getting-started/apply-for-aid (or link directly to www.fafsa.gov?)

**Comment by sfgwv** [comment]
Possible Net Price Calculator copy, taken from the admit packet:

Use the Net Price Calculator to project your eligibility for federal and state financial aid
programs. financialaid.wvu.edu/net-price-calculator

**Comment by dmolsen** [comment]
Added blocks to the cost & aid page. Dustin can update this the way he wants but at least it's there.
