### ISSUE TITLE
Rewrite Paying for College copy on Cost & Aid

### ISSUE THREAD

**Issue by sfgwv** [wvuweb/undergraduate-admissions#57]
I need to rewrite this but can't come up with a good option tonight. Noting it here so it doesn't get missed.

**Comment by dmolsen** [comment]
Because I've forgotten this I just wanted to note we should hit on the value of WVU based on our academics and cost. We should at least subtly mention one when we mention the other. It may not be possible but just keep it in mind.

**Comment by sfgwv** [comment]
Done for now, but will likely have to tweak further.
