### ISSUE TITLE
Change button text on How to Apply

### ISSUE THREAD

**Issue by sfgwv** [wvuweb/undergraduate-admissions#59]
The "Learn About" wording on the buttons isn't quite working. Maybe "Read the Steps for", "Get the Steps for", "Information for" or "Get Information for" instead?

This is related to #58

**Comment by dmolsen** [comment]
Let me know what you think.

http://admissions.sandbox.wvu.edu/how-to-apply

**Comment by sfgwv** [comment]
Perfect.
