### ISSUE TITLE
Possible Content & Design Changes for "Apply Now"

### ISSUE THREAD

**Issue by dmolsen** [wvuweb/undergraduate-admissions#8]
We need to split this page into two parts. The first would be First-time Freshman which would have both the common app and regular app. The second section can be a catch all for everyone else. We just need to clearly define them.

Rather than stacking the WVU and Common App sections vertically it might be useful to:

1. work the common app wording into the lede copy
2. move the two buttons together. not sure what the WVU button would say though to clearly distinguish it from the common app. Ideas?

This is related to #40

**Comment by dustinmazon** [comment]
I can work on it. I can't remember other than F-TF, what were the audiences that needed addressed?

* First-Time Freshman
* Everyone Else...

**Comment by dmolsen** [comment]
That's it. Almost everyone else on our audience nav has to use the regular app. Senior citizens, visiting, and faculty and staff should use separate forms though.

**Comment by dmolsen** [comment]
Also make sure that Grad is properly linked just in case.

**Comment by dmolsen** [comment]
Based on discussion between @dustinmazon and myself this page is going to be removed. Instead we're going to dump folks to the "How to Apply" page. We can't easily work all of the audiences into one page.
